services:
  flask-api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./keys:/app/keys:ro
    environment:
      DB_HOST: ${DB_HOST:-patienthealthanalytics-patienthealthanalyticspostgres-k4bn77}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-healthcare_db}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
      REDIRECT_URI: ${REDIRECT_URI:-https://health-analytics.duckdev.me/callback}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: trueg